//! Static catalog of known ACP coding CLI runtimes.
//!
//! Kept out of `discovery.rs` so the large `KNOWN_ACP_RUNTIMES` table does not
//! push that module over the desktop file-size ratchet.

use super::runtime_metadata::KnownAcpRuntime;

pub(crate) const GOOSE_AVATAR_URL: &str = "https://goose-docs.ai/img/logo_dark.png";
pub(crate) const CLAUDE_CODE_AVATAR_URL: &str = "https://anthropic.gallerycdn.vsassets.io/extensions/anthropic/claude-code/2.1.77/1773707456892/Microsoft.VisualStudio.Services.Icons.Default";
pub(crate) const CODEX_AVATAR_URL: &str = "https://openai.gallerycdn.vsassets.io/extensions/openai/chatgpt/26.5313.41514/1773706730621/Microsoft.VisualStudio.Services.Icons.Default";
pub(crate) const OPENCODE_AVATAR_URL: &str =
    "https://raw.githubusercontent.com/anomalyco/opencode/dev/packages/console/app/public/favicon-96x96.png";
pub(crate) const BUZZ_AGENT_AVATAR_URL: &str =
    "https://raw.githubusercontent.com/block/buzz/refs/heads/main/crates/buzz-agent/buzz-agent.png";

pub(crate) const KNOWN_ACP_RUNTIMES: &[KnownAcpRuntime] = &[
    KnownAcpRuntime {
        id: "goose",
        label: "Goose",
        commands: &["goose"],
        aliases: &[],
        avatar_url: GOOSE_AVATAR_URL,
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: Some("goose"),
        cli_install_commands: &["curl -fsSL https://github.com/aaif-goose/goose/releases/download/stable/download_cli.sh | CONFIGURE=false bash"],
        // Goose's stable release currently publishes only the Unix installer;
        // its official Windows instructions intentionally point at this main-branch script.
        cli_install_commands_windows: &["powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"$env:CONFIGURE='false'; irm https://raw.githubusercontent.com/aaif-goose/goose/main/download_cli.ps1 | iex\""],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://goose-docs.ai/docs/getting-started/installation/",
        adapter_install_instructions_url: "",
        cli_install_hint: "Buzz requires the Goose CLI; the desktop app alone is not enough.",
        adapter_install_hint: "",
        skill_dir: Some(".goose/skills"),
        supports_acp_model_switching: false,
        model_env_var: Some("GOOSE_MODEL"),
        provider_env_var: Some("GOOSE_PROVIDER"),
        provider_locked: false,
        default_env: &[("GOOSE_MODE", "auto")],
        config_file_path: Some("~/.config/goose/config.yaml"),
        config_file_format: Some("yaml"),
        supports_acp_native_config: true,
        thinking_env_var: Some("GOOSE_THINKING_EFFORT"),
        max_tokens_env_var: Some("GOOSE_MAX_TOKENS"),
        context_limit_env_var: Some("GOOSE_CONTEXT_LIMIT"),
        required_normalized_fields: &["model", "provider"],
        login_hint: None,
        auth_probe_args: None,
    },
    KnownAcpRuntime {
        id: "claude",
        label: "Claude Code",
        commands: &["claude-agent-acp", "claude-code-acp"],
        aliases: &["claude-code", "claudecode"],
        avatar_url: CLAUDE_CODE_AVATAR_URL,
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: Some("claude"),
        cli_install_commands: &["curl -fsSL https://claude.ai/install.sh | bash"],
        cli_install_commands_windows: &["powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"irm https://claude.ai/install.ps1 | iex\""],
        adapter_install_commands: &["npm install -g @agentclientprotocol/claude-agent-acp"],
        cli_install_instructions_url: "https://code.claude.com/docs/en/getting-started",
        adapter_install_instructions_url: "https://github.com/agentclientprotocol/claude-agent-acp",
        cli_install_hint: "Buzz requires the Claude Code CLI; the desktop app alone is not enough.",
        adapter_install_hint: "Install the Claude Code ACP adapter via npm.",
        skill_dir: Some(".claude/skills"),
        supports_acp_model_switching: false,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: true,
        default_env: &[],
        config_file_path: Some("~/.claude/settings.json"),
        config_file_format: Some("json"),
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        required_normalized_fields: &[],
        login_hint: Some("Run the Claude CLI to complete authentication."),
        auth_probe_args: Some(&["claude", "auth", "status"]),
    },
    KnownAcpRuntime {
        id: "codex",
        label: "Codex",
        commands: &["codex-acp"],
        aliases: &[],
        avatar_url: CODEX_AVATAR_URL,
        mcp_command: Some("buzz-dev-mcp"),
        mcp_hooks: false,
        underlying_cli: Some("codex"),
        cli_install_commands: &["curl -fsSL https://chatgpt.com/codex/install.sh | sh"],
        cli_install_commands_windows: &["powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"irm https://chatgpt.com/codex/install.ps1 | iex\""],
        adapter_install_commands: &["npm install -g @agentclientprotocol/codex-acp"],
        cli_install_instructions_url: "https://developers.openai.com/codex/cli/",
        adapter_install_instructions_url: "https://github.com/agentclientprotocol/codex-acp",
        cli_install_hint: "Buzz requires the Codex CLI; the desktop app alone is not enough.",
        adapter_install_hint: "Install the Codex ACP adapter via npm.",
        skill_dir: Some(".codex/skills"),
        supports_acp_model_switching: false,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: false,
        default_env: &[],
        config_file_path: Some("~/.codex/config.toml"),
        config_file_format: Some("toml"),
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        required_normalized_fields: &[],
        login_hint: Some("Run `codex login` to authenticate."),
        // Verified: `codex login status` exits 0 when logged in, non-zero otherwise.
        auth_probe_args: Some(&["codex", "login", "status"]),
    },
    // OpenCode exposes native ACP via `opencode acp` (same shape as Goose).
    // No separate npm adapter is required. See https://opencode.ai/docs/acp/
    KnownAcpRuntime {
        id: "opencode",
        label: "OpenCode",
        commands: &["opencode"],
        aliases: &[],
        avatar_url: OPENCODE_AVATAR_URL,
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: Some("opencode"),
        cli_install_commands: &["curl -fsSL https://opencode.ai/install | bash"],
        cli_install_commands_windows: &[
            "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"irm https://opencode.ai/install | iex\"",
            "npm install -g opencode-ai@latest",
        ],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://opencode.ai/docs/",
        adapter_install_instructions_url: "",
        cli_install_hint: "Buzz requires the OpenCode CLI; the desktop app alone is not enough.",
        adapter_install_hint: "",
        // Nest skill symlink; OpenCode also reads ~/.config/opencode/skills.
        skill_dir: Some(".opencode/skills"),
        supports_acp_model_switching: false,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: false,
        default_env: &[],
        config_file_path: Some("~/.config/opencode/opencode.jsonc"),
        config_file_format: Some("json"),
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        required_normalized_fields: &[],
        login_hint: Some("Run `opencode providers login` to configure credentials."),
        // No reliable non-interactive login probe yet: `opencode providers list`
        // exits 0 whether or not credentials are configured (pretty TUI output).
        // Credentials live in ~/.local/share/opencode/auth.json.
        auth_probe_args: None,
    },
    // OpenCode exposes native ACP via `opencode acp` (same shape as Goose).
    // No separate npm adapter is required. See https://opencode.ai/docs/acp/
    KnownAcpRuntime {
        id: "opencode",
        label: "OpenCode",
        commands: &["opencode"],
        aliases: &[],
        avatar_url: OPENCODE_AVATAR_URL,
        mcp_command: None,
        mcp_hooks: false,
        underlying_cli: Some("opencode"),
        cli_install_commands: &["curl -fsSL https://opencode.ai/install | bash"],
        cli_install_commands_windows: &[
            "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"irm https://opencode.ai/install | iex\"",
            "npm install -g opencode-ai@latest",
        ],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://opencode.ai/docs/",
        adapter_install_instructions_url: "",
        cli_install_hint: "Buzz requires the OpenCode CLI; the desktop app alone is not enough.",
        adapter_install_hint: "",
        // Nest skill symlink; OpenCode also reads ~/.config/opencode/skills.
        skill_dir: Some(".opencode/skills"),
        supports_acp_model_switching: false,
        model_env_var: None,
        provider_env_var: None,
        provider_locked: false,
        default_env: &[],
        config_file_path: Some("~/.config/opencode/opencode.jsonc"),
        config_file_format: Some("json"),
        supports_acp_native_config: false,
        thinking_env_var: None,
        max_tokens_env_var: None,
        context_limit_env_var: None,
        required_normalized_fields: &[],
        login_hint: Some("Run `opencode providers login` to configure credentials."),
        // No reliable non-interactive login probe yet: `opencode providers list`
        // exits 0 whether or not credentials are configured (pretty TUI output).
        // Credentials live in ~/.local/share/opencode/auth.json.
        auth_probe_args: None,
    },
    KnownAcpRuntime {
        id: "buzz-agent",
        label: "Buzz Agent",
        commands: &["buzz-agent"],
        aliases: &[],
        avatar_url: BUZZ_AGENT_AVATAR_URL,
        mcp_command: Some("buzz-dev-mcp"),
        mcp_hooks: true,
        underlying_cli: None,
        cli_install_commands: &[],
        cli_install_commands_windows: &[],
        adapter_install_commands: &[],
        cli_install_instructions_url: "https://github.com/block/buzz",
        adapter_install_instructions_url: "https://github.com/block/buzz",
        cli_install_hint: "Ships with the Buzz desktop app.",
        adapter_install_hint: "",
        skill_dir: None,
        supports_acp_model_switching: true,
        model_env_var: Some("BUZZ_AGENT_MODEL"),
        provider_env_var: Some("BUZZ_AGENT_PROVIDER"),
        provider_locked: false,
        default_env: &[],
        config_file_path: None,
        config_file_format: None,
        supports_acp_native_config: false,
        thinking_env_var: Some("BUZZ_AGENT_THINKING_EFFORT"),
        max_tokens_env_var: Some("BUZZ_AGENT_MAX_OUTPUT_TOKENS"),
        context_limit_env_var: Some("BUZZ_AGENT_MAX_CONTEXT_TOKENS"),
        required_normalized_fields: &["model", "provider"],
        login_hint: None,
        auth_probe_args: None,
    },
];

/// Skill discovery directories declared by known runtimes.
pub(crate) fn known_skill_dirs() -> impl Iterator<Item = &'static str> {
    KNOWN_ACP_RUNTIMES.iter().filter_map(|p| p.skill_dir)
}
